// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoeLJQwHMUJgtd-UI9Q9t8vsxebS6fGw',
    appId: '1:504400761702:web:74096d04fe397851a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    authDomain: 'smartlink-pro.firebaseapp.com',
    storageBucket: 'smartlink-pro.appspot.com',
    measurementId: 'G-Y73BP1ZG66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIO_HwRMwRt_j_TYu_s2NjQ0bufHyv6o',
    appId: '1:504400761702:android:38e1f05dfdc8bb20a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    storageBucket: 'smartlink-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_foRrtanDZ_9IeOiAuMdgdhUD9HxSqE',
    appId: '1:504400761702:ios:b6fab9a264ec7cc6a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    storageBucket: 'smartlink-pro.appspot.com',
    iosClientId: '504400761702-fa0pd93lq55fl8s7m4de5fakbju97dvb.apps.googleusercontent.com',
    iosBundleId: 'com.smartlink.app.smartlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_foRrtanDZ_9IeOiAuMdgdhUD9HxSqE',
    appId: '1:504400761702:ios:ef7d82d2992d75a8a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    storageBucket: 'smartlink-pro.appspot.com',
    iosClientId: '504400761702-f1bvbnrud2eu7alqespno5eqdkq7qt18.apps.googleusercontent.com',
    iosBundleId: 'com.smartlink.app.smartlink.RunnerTests',
  );
}
